"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, FileText } from "lucide-react";
import type { Meal } from "@/lib/supabase-client";
import {
	formatDate,
	getMealCountForDate,
	formatCurrency,
	calculateMealStats,
} from "@/lib/meal-utils";
import { useToast } from "@/hooks/use-toast";

interface SimpleReportProps {
	meals: Meal[];
}

export function SimpleReport({ meals }: SimpleReportProps) {
	const [generating, setGenerating] = useState<string | null>(null);
	const { toast } = useToast();

	function forceDownload(content: string, filename: string) {
		try {
			// Create blob with UTF-8 BOM for better compatibility
			const blob = new Blob(["\ufeff" + content], {
				type: "text/plain;charset=utf-8",
			});

			// Create download link
			const url = URL.createObjectURL(blob);
			const link = document.createElement("a");
			link.href = url;
			link.download = filename;
			link.style.display = "none";

			// Add to DOM, click, and remove
			document.body.appendChild(link);
			link.click();

			// Cleanup
			setTimeout(() => {
				document.body.removeChild(link);
				URL.revokeObjectURL(url);
			}, 100);

			return true;
		} catch (error) {
			console.error("Download failed:", error);

			// Fallback: try to open in new window
			try {
				const newWindow = window.open();
				if (newWindow) {
					newWindow.document.write(`<pre>${content}</pre>`);
					newWindow.document.title = filename;
				}
				return true;
			} catch (fallbackError) {
				console.error("Fallback failed:", fallbackError);
				return false;
			}
		}
	}

	async function generateQuickReport(days: number) {
		setGenerating(`${days}days`);

		try {
			// Get meals from the last N days
			const today = new Date();
			const startDate = new Date(today);
			startDate.setDate(today.getDate() - days + 1);

			const filteredMeals = meals.filter((meal) => {
				const mealDate = new Date(meal.date);
				return mealDate >= startDate && mealDate <= today;
			});

			if (filteredMeals.length === 0) {
				toast({
					title: "No data",
					description: `No meals found in the last ${days} days`,
					variant: "destructive",
				});
				return;
			}

			// Generate simple text report
			const stats = calculateMealStats(filteredMeals);
			const sortedMeals = [...filteredMeals].sort(
				(a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
			);

			let reportContent = `MEAL REPORT - LAST ${days} DAYS\n`;
			reportContent += `===============================\n\n`;
			reportContent += `Period: ${formatDate(
				sortedMeals[0]?.date || ""
			)} to ${formatDate(sortedMeals[sortedMeals.length - 1]?.date || "")}\n`;
			reportContent += `Generated: ${new Date().toLocaleString()}\n\n`;

			reportContent += `SUMMARY:\n`;
			reportContent += `--------\n`;
			reportContent += `Total Meals: ${stats.totalMeals}\n`;
			reportContent += `Paid Meals: ${stats.paidMeals}\n`;
			reportContent += `Unpaid Meals: ${stats.unpaidMeals}\n`;
			reportContent += `Amount Paid: ${formatCurrency(stats.totalPaid)}\n`;
			reportContent += `Amount Due: ${formatCurrency(stats.totalDue)}\n`;
			reportContent += `Balance: ${formatCurrency(stats.balance)}\n\n`;

			reportContent += `DAILY MEAL COUNT:\n`;
			reportContent += `-----------------\n`;
			reportContent += `Date\t\tMeals\tBreakfast\tLunch\tDinner\n`;
			reportContent += `----\t\t-----\t---------\t-----\t------\n`;

			sortedMeals.forEach((meal) => {
				const totalMeals = getMealCountForDate(meal);
				const b = meal.breakfast ? (meal.breakfast_paid ? "Y(P)" : "Y") : "N";
				const l = meal.lunch ? (meal.lunch_paid ? "Y(P)" : "Y") : "N";
				const d = meal.dinner ? (meal.dinner_paid ? "Y(P)" : "Y") : "N";

				reportContent += `${formatDate(
					meal.date
				)}\t${totalMeals}\t${b}\t\t${l}\t${d}\n`;
			});

			reportContent += `\nLEGEND:\n`;
			reportContent += `-------\n`;
			reportContent += `Y = Meal taken, N = Meal not taken\n`;
			reportContent += `(P) = Paid meal\n`;
			reportContent += `Rate: Rs.250 per meal\n\n`;
			reportContent += `Generated by Daily Meal Tracker v1.0\n`;

			// Download the file
			const success = forceDownload(
				reportContent,
				`meal-report-${days}days.txt`
			);

			if (success) {
				toast({
					title: "Success",
					description: `Report for last ${days} days downloaded successfully`,
				});
			} else {
				toast({
					title: "Download failed",
					description: "Please check your browser's download settings",
					variant: "destructive",
				});
			}
		} catch (error) {
			console.error("Error generating quick report:", error);
			toast({
				title: "Error",
				description: "Failed to generate report",
				variant: "destructive",
			});
		} finally {
			setGenerating(null);
		}
	}

	return (
		<Card>
			<CardHeader>
				<CardTitle className="flex items-center gap-2">
					<FileText className="h-5 w-5" />
					Quick Reports
				</CardTitle>
			</CardHeader>
			<CardContent>
				<div className="flex flex-wrap gap-2">
					<Button
						variant="outline"
						size="sm"
						onClick={() => generateQuickReport(7)}
						disabled={generating === "7days"}
					>
						<Download className="mr-2 h-3 w-3" />
						{generating === "7days" ? "Generating..." : "Last 7 Days"}
					</Button>
					<Button
						variant="outline"
						size="sm"
						onClick={() => generateQuickReport(30)}
						disabled={generating === "30days"}
					>
						<Download className="mr-2 h-3 w-3" />
						{generating === "30days" ? "Generating..." : "Last 30 Days"}
					</Button>
					<Button
						variant="outline"
						size="sm"
						onClick={() => generateQuickReport(90)}
						disabled={generating === "90days"}
					>
						<Download className="mr-2 h-3 w-3" />
						{generating === "90days" ? "Generating..." : "Last 90 Days"}
					</Button>
				</div>
				<p className="text-xs text-muted-foreground mt-2">
					Generate simple text reports listing dates and meal counts
				</p>
				{meals.length === 0 && (
					<p className="text-xs text-orange-600 mt-1">
						No meal data available. Add some meals first.
					</p>
				)}
			</CardContent>
		</Card>
	);
}
